version: '1'

services:
  frontend:
    build: ./frontend
    restart: on-failure
    ports:
      - '3000:3000'
    environment:
      VITE_SERVER_HOST: http://localhost:5555
  api:
    build: ./api
    restart: on-failure
    ports:
      - '5555:5000'
    environment:
      DB_CONNECTION_LIMIT: 100
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: password
      DATABASE: time_db
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: time_db
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  adminer:
    image: adminer
    restart: on-failure
    ports:
      - '8888:8080'
