version: '1'

services:
  frontend:
    build: ./frontend
    restart: on-failure
    ports:
      - '3000:3000'
  api:
    build: ./api
    restart: on-failure
    ports:
      - '5555:5000'
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: time_db
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  adminer:
    image: adminer
    restart: on-failure
    ports:
      - '8888:8080'
